---

- name: "Check if Google Chrome is Installed"
  shell: "type google-chrome-stable"
  failed_when: False
  register: check_chrome

- meta: end_play
  when: "check_chrome.rc == 0"

# Ubuntu

- name: "Install Google Chrome (apt)"
  become: True
  apt:
    deb: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    state: "present"
  when: "ansible_os_family == 'Debian'"

# Fedora

- name: "Install Google Chrome (dnf)"
  become: True
  dnf:
    name: "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"
    state: "present"
  when: "ansible_distribution == 'Fedora'"

# Arch

- name: "Install Google Chrome (yaourt)"
  shell: "yaourt --noconfirm -S google-chrome"
  when: "ansible_os_family == 'Archlinux'"
