---

# Ubuntu

- name: "Install atom (apt)"
  become: True
  apt:
    deb: "https://github.com/atom/atom/releases/download/v1.24.0/atom-amd64.deb"
    state: "present"
  when: "ansible_os_family == 'Debian'"

# Fedora

- name: "Install atom (dnf)"
  become: True
  dnf:
    name: "https://github.com/atom/atom/releases/download/v1.24.0/atom.x86_64.rpm"
    state: "present"
  when: "ansible_distribution == 'Fedora'"

# Arch

- name: "Install atom (pacman)"
  become: True
  pacman:
    name: "atom"
    state: "latest"
  when: "ansible_os_family == 'Archlinux'"

# Plugins

- name: "Install atom plugins"
  shell: >
    apm install -y autocomplete-clang busy-signal build build-cmake build-make git-plus go-plus
    language-batch language-cmake language-flatbuffers language-glsl language-hlsl
    language-jenkinsfile language-lua language-luajit language-powershell language-terraform
    minimap switch-header-source teletype power-mode vim-mode-plus

# HACK
- name: "Hack to let me disable atom plugins"
  shell: "atom && sleep 10 && pkill -KILL atom"

- name: "Disable annoying plugins"
  shell: "apm disable power-mode vim-mode-plus"
