---

# Ubuntu

- name: "Install VirtualBox (apt)"
  become: True
  apt:
    deb: "https://download.virtualbox.org/virtualbox/5.2.8/virtualbox-5.2_5.2.8-121009~Ubuntu~zesty_amd64.deb"
    state: "present"
  when: "ansible_os_family == 'Debian'"

# Fedora

- name: "Install VirtualBox (dnf)"
  become: True
  dnf:
    name: "https://download.virtualbox.org/virtualbox/5.2.8/VirtualBox-5.2-5.2.8_121009_fedora26-1.x86_64.rpm"
    state: "present"
  when: "ansible_distribution == 'Fedora'"

# Arch

- name: "Install VirtualBox (pacman)"
  become: True
  pacman:
    name: "virtualbox"
    state: "latest"
  when: "ansible_os_family == 'Archlinux'"

# Configuration

- name: "Add user to VirtualBox group"
  become: True
  shell: usermod -a -G vboxusers {{ ansible_user_id }}
